# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/Vinh/AppData/Local/Temp/mainUibindcD.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainForm(object):
    def setupUi(self, MainForm):
        MainForm.setObjectName("MainForm")
        MainForm.resize(1006, 735)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(MainForm)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget = QtWidgets.QWidget(MainForm)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.toolBar = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBar.sizePolicy().hasHeightForWidth())
        self.toolBar.setSizePolicy(sizePolicy)
        self.toolBar.setStyleSheet("QPushButton {\n"
"    font-family: Arial;\n"
"    font-size: 17px;\n"
"    min-height: 26px;\n"
"}\n"
"\n"
"QCheckBox {\n"
"    font-family: Arial;\n"
"    font-size: 17px;\n"
"}\n"
"\n"
"QGroupBox {\n"
"    font-family: Arial;\n"
"    font-size: 15px;\n"
"}")
        self.toolBar.setObjectName("toolBar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.toolBar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(9)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.readBar = QtWidgets.QGroupBox(self.toolBar)
        self.readBar.setObjectName("readBar")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.readBar)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton_read_file = QtWidgets.QPushButton(self.readBar)
        self.pushButton_read_file.setObjectName("pushButton_read_file")
        self.verticalLayout_5.addWidget(self.pushButton_read_file)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.readBar)
        self.processBar = QtWidgets.QGroupBox(self.toolBar)
        self.processBar.setCheckable(True)
        self.processBar.setObjectName("processBar")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.processBar)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox_remove_noise = QtWidgets.QCheckBox(self.processBar)
        self.checkBox_remove_noise.setChecked(True)
        self.checkBox_remove_noise.setObjectName("checkBox_remove_noise")
        self.verticalLayout_2.addWidget(self.checkBox_remove_noise)
        self.checkBox_convert_to_binary = QtWidgets.QCheckBox(self.processBar)
        self.checkBox_convert_to_binary.setChecked(True)
        self.checkBox_convert_to_binary.setObjectName("checkBox_convert_to_binary")
        self.verticalLayout_2.addWidget(self.checkBox_convert_to_binary)
        self.checkBox_deskew = QtWidgets.QCheckBox(self.processBar)
        self.checkBox_deskew.setChecked(True)
        self.checkBox_deskew.setObjectName("checkBox_deskew")
        self.verticalLayout_2.addWidget(self.checkBox_deskew)
        self.horizontalLayout.addWidget(self.processBar)
        self.extractBar = QtWidgets.QGroupBox(self.toolBar)
        self.extractBar.setObjectName("extractBar")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.extractBar)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_detectText = QtWidgets.QPushButton(self.extractBar)
        self.pushButton_detectText.setObjectName("pushButton_detectText")
        self.verticalLayout_4.addWidget(self.pushButton_detectText)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.horizontalLayout.addWidget(self.extractBar)
        self.viewBar = QtWidgets.QGroupBox(self.toolBar)
        self.viewBar.setObjectName("viewBar")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.viewBar)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushButton_image = QtWidgets.QPushButton(self.viewBar)
        self.pushButton_image.setObjectName("pushButton_image")
        self.verticalLayout_6.addWidget(self.pushButton_image)
        self.pushButton_image_process = QtWidgets.QPushButton(self.viewBar)
        self.pushButton_image_process.setObjectName("pushButton_image_process")
        self.verticalLayout_6.addWidget(self.pushButton_image_process)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem2)
        self.horizontalLayout.addWidget(self.viewBar)
        self.verticalLayout.addWidget(self.toolBar)
        self.image_frame = QtWidgets.QLabel(self.widget)
        self.image_frame.setStyleSheet("font-size: 30px;\n"
"border: 3px solid #ff9000;")
        self.image_frame.setAlignment(QtCore.Qt.AlignCenter)
        self.image_frame.setObjectName("image_frame")
        self.verticalLayout.addWidget(self.image_frame)
        self.verticalLayout_3.addWidget(self.widget)

        self.retranslateUi(MainForm)
        QtCore.QMetaObject.connectSlotsByName(MainForm)

    def retranslateUi(self, MainForm):
        _translate = QtCore.QCoreApplication.translate
        MainForm.setWindowTitle(_translate("MainForm", "OCR System"))
        self.readBar.setTitle(_translate("MainForm", "Đọc ảnh"))
        self.pushButton_read_file.setText(_translate("MainForm", "Mở tệp..."))
        self.processBar.setTitle(_translate("MainForm", "Xử lý ảnh"))
        self.checkBox_remove_noise.setText(_translate("MainForm", "Loại bỏ nhiễu"))
        self.checkBox_convert_to_binary.setText(_translate("MainForm", "Chuyển sang ảnh nhị phân"))
        self.checkBox_deskew.setText(_translate("MainForm", "Chỉnh góc nghiêng"))
        self.extractBar.setTitle(_translate("MainForm", "Xuất văn bản"))
        self.pushButton_detectText.setText(_translate("MainForm", "Thực hiện nhận diện"))
        self.viewBar.setTitle(_translate("MainForm", "Hiển thị"))
        self.pushButton_image.setText(_translate("MainForm", "Ảnh gốc"))
        self.pushButton_image_process.setText(_translate("MainForm", "Ảnh đã xử lý"))
        self.image_frame.setText(_translate("MainForm", "(Ảnh sẽ được hiển thị tại đây)"))
